"""esquema_modificado

Revision ID: ecc3a514a9a9
Revises: d04a45767ede
Create Date: 2025-05-19 18:34:22.825694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc3a514a9a9'
down_revision: Union[str, None] = 'd04a45767ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispositivo', sa.Column('descripcion_ubicacion', sa.String(), nullable=False))
    op.add_column('dispositivo', sa.Column('coordenadas_gps', sa.String(), nullable=True))
    op.add_column('dispositivo', sa.Column('estado_actual', sa.String(), nullable=True))
    op.drop_column('dispositivo', 'ubicacion')
    op.add_column('sensor', sa.Column('umblal_alerta', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'umblal_alerta')
    op.add_column('dispositivo', sa.Column('ubicacion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('dispositivo', 'estado_actual')
    op.drop_column('dispositivo', 'coordenadas_gps')
    op.drop_column('dispositivo', 'descripcion_ubicacion')
    # ### end Alembic commands ###
